// export default [
//     {
//         id: '1',
//         author: 'Virginia Woolf',
//         tourName: "Dancing with the Woolf",
//         timeFrame: "4 Days",
//         years: "1800s",
//         country: "United Kingdom",
//         gender: "Female",
//         famousWorks: "The Years, A Room of One's Own, To the Lighthouse, Mrs Dalloway, The Voyage Out",
//         picture: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/George_Charles_Beresford_-_Virginia_Woolf_in_1902_-_Restoration.jpg/220px-George_Charles_Beresford_-_Virginia_Woolf_in_1902_-_Restoration.jpg",
//     },
//     {
//         id:'2',
//         author: 'Maya Angelou',
//         tourName: "Change Your Attitude",
//         timeFrame: "4 Days",
//         years: "1900s",
//         country: "United States",
//         gender: "Female",
//         famousWorks: "I Know Why The Caged Bird Sings, And Still I rise, The Heart of A Woman, On The Pulse of Morning, A Song Flung Up to Heaven",
//         picture: "https://media.glamourmagazine.co.uk/photos/61dec00fec31c26165e7cb1c/master/w_1600%2Cc_limit/MAYAANGELOU_120122_GettyImages-74252590_P.jpg",
//     },
//     {
//         id: '3',
//         author: 'Walt Whitman',
//         tourName: "Not I can travel, the leaves of Grass",
//         timeFrame: "3 Days",
//         years: "1800s",
//         country: "United States",
//         gender: "Male",
//         famousWorks: "Song of Myself, I Sing the Body Electric, I Hear America Singing, O Captain, A Noiseless Patient Spider",
//         picture: "https://upload.wikimedia.org/wikipedia/commons/1/1c/Walt_Whitman%2C_steel_engraving%2C_July_1854.jpg",
//     },
//     {
//         id: '4',
//         author: 'Sylvia Plath',
//         tourName: "A Mirrored pool of thought",
//         timeFrame: "4 Days",
//         years: "1900s",
//         country: "United States",
//         gender: "Female",
//         famousWorks: "Daddy, Lady Lazarus, Mirror, Ariel, The Bell Jar",
//         picture: "https://www.nybooks.com/wp-content/uploads/2017/11/plath-brunette.jpg",
//     },
//     {
//         id: '5',
//         author: 'Toni Morrison',
//         tourName: "Thin love ain't love at all",
//         timeFrame: "5 Days",
//         years: "1900s",
//         country: "United States",
//         gender: "Female",
//         famousWorks: "The Bluest Eye, Sula, Song of Solomon, Beloved, Remember: The Journey to School Integration",
//         picture: "https://static01.nyt.com/images/2019/08/06/books/06Books-Appraisal/06Books-Appraisal-articleLarge.jpg?quality=75&auto=webp&disable=upscale",
//     },
//     {
//         id: '6',
//         author: 'Emily Dickinson',
//         tourName: "Forever is composed of Nows",
//         timeFrame: "3 Days",
//         years: "1800s",
//         country: "United States",
//         gender: "Female",
//         famousWorks: "I Heard a fly buzz - when I died, Success is counted sweetest, I felt a funderal, in my Brain, Because I could not stop for Death, My Life had stood - a loaded Gun",
//         picture: "https://static.faber.co.uk/wp-content/uploads/2021/08/Black-white_photograph_of_Emily_Dickinson_Restored.jpg",
//     },
//     {
//         id: '7',
//         author: 'Mary Shelley',
//         tourName: "The Modern Day Prometheus",
//         timeFrame: "3 Days",
//         years: "1800s",
//         country: "United Kingdom",
//         gender: "Female",
//         famousWorks: "Frankenstein, The Last Man, The Fortunes of Perkin Warbeck, Valperga, History of Six Weeks Tour",
//         picture: "https://www2.clarku.edu/faculty/lkasmer/ENG263/Fall04/ghollands/images/Mary_Shelley.jpg",
//     },
//     {
//         id: '8',
//         author: 'Jane Austen',
//         tourName: "There is no enjoyment like reading",
//         timeFrame: "3 Days",
//         years: "1700s",
//         country: "United States",
//         gender: "Female",
//         famousWorks: "Song of Myself, I Sing the Body Electric, I Hear America Singing, O Captain, A Noiseless Patient Spider",
//         picture: "https://th-thumbnailer.cdn-si-edu.com/wC408fAbBm1zjzKZKqGYcYUQfeU=/fit-in/1072x0/https://tf-cmsv2-smithsonianmag-media.s3.amazonaws.com/filer/30/4a/304a1ef2-1c4a-429c-a612-2ec99d797737/jane_austen_1870_memoir_woodcut_-_jane_austens_house.jpg",
//     },
//     {
//         id: '9',
//         author: 'Charles Bukowski',
//         tourName: "Find what you love and let it kill you",
//         timeFrame: "5 Days",
//         years: "1900s",
//         country: "United States",
//         gender: "Male",
//         famousWorks: "Notes Of A Dirty Old Man, Post Office, Hot Water Music, Factotum, Ham On Rye",
//         picture: "https://sobotkalitmag.files.wordpress.com/2015/09/bukowski.jpg",
//     },
//     {
//         id: '10',
//         author: 'Lord Byron',
//         tourName: "Laughing is cheap medicine",
//         timeFrame: "5 Days",
//         years: "1800s",
//         country: "United States",
//         gender: "Male",
//         famousWorks: "Don Juan, When We Two Parted, Darkness, Beppo, She Walks In Beauty",
//         picture: "https://cdn.britannica.com/15/147615-050-9D75F95E/George-Gordon-Byron.jpg",
//     },
// ]